projects:
  testingawsupload:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: GraphQLAPI.swift
        docsFilePath: graphql
extensions:
  amplify:
    version: 3
